### ISSUE TITLE
Security Rule Types

### ISSUE THREAD

**Issue by Sawborg** [PaloAltoNetworks/pan-configurator#12]
As of PANOS 6.1, security rules can have a type of "universal", "intrazone" or "interzone". Can a feature be added to be able to parse rules based on type or is this already possible? I didn't see an option as a selectable filter or action. 

I think it would be helpful to be able to filter based on security rule type and be able to convert from one type to another (e.g. universal rule to interzone).

**Comment by cpainchaud** [comment]
Hi,

 filters added.

thx !

**Comment by cpainchaud** [comment]
Hi Sawborg,

 Would you let us know what you have in mind by 'converting' a rule from universal to intra or vice versa ? Do you mean just changing the property or making some sort of transformation ?

Thx

**Comment by Sawborg** [comment]
In the xml config (for versions 6.1+), there is now an xml tag called "<rule-type>  / </rule-type>" under each rule entry, which can have the values of "universal", "interzone" or "intrazone". It would be nice to be able to update these in bulk as well.

**Comment by cpainchaud** [comment]
It's coming soon. We noticed second part of your request later on :)

**Comment by swaschkut** [comment]
Filters and action implemented

'filter=(rule is.universal)'
'filter=(rule is.intrazone)'
'filter=(rule is.interzone)'

action=ruletype-change:universal
action=ruletype-change:intrazone
action=ruletype-change:interzone

action is also available for in=api://x.x.x.x
